/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\dev\arniem\models\peg.glb -o c:\dev\arniem\models\peg.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cutter014: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/peg.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cutter014.geometry} material={nodes.Cutter014.material} position={[-0.355, 0.088, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
    </group>
  )
}

useGLTF.preload('/peg.glb')
