/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 unit_pegboard.gltf --keepnames --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube074: THREE.Mesh
    Cube075: THREE.Mesh
    Cube076: THREE.Mesh
    m_panel_tb: THREE.Mesh
    Cutter014: THREE.Mesh
    Cutter015: THREE.Mesh
    Cutter016: THREE.Mesh
    Cutter017: THREE.Mesh
    Cutter018: THREE.Mesh
    Cutter019: THREE.Mesh
    Cutter020: THREE.Mesh
    m_panel_b: THREE.Mesh
    m_panel_l: THREE.Mesh
    m_panel_r: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/unit_pegboard.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="c_box_sx" position={[0, 0, 0.064]}>
        <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={nodes.Cube074.material} position={[0, 0.106, 0]} />
        <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[0, -0.062, 0]} />
        <mesh name="Cube076" geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} position={[0, -0.149, 0]} />
        <mesh name="m_panel_tb" geometry={nodes.m_panel_tb.geometry} material={nodes.m_panel_tb.material} position={[0, 0.319, 0]} />
      </group>
      <mesh name="Cutter014" geometry={nodes.Cutter014.geometry} material={nodes.Cutter014.material} position={[-0.355, 0.088, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="Cutter015" geometry={nodes.Cutter015.geometry} material={nodes.Cutter015.material} position={[0.001, 0.088, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="Cutter016" geometry={nodes.Cutter016.geometry} material={nodes.Cutter016.material} position={[0.356, 0.088, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="Cutter017" geometry={nodes.Cutter017.geometry} material={nodes.Cutter017.material} position={[-0.355, -0.082, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="Cutter018" geometry={nodes.Cutter018.geometry} material={nodes.Cutter018.material} position={[-0.177, -0.082, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="Cutter019" geometry={nodes.Cutter019.geometry} material={nodes.Cutter019.material} position={[-0.088, -0.167, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="Cutter020" geometry={nodes.Cutter020.geometry} material={nodes.Cutter020.material} position={[0.356, -0.167, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={[1.199, 2.412, 1.199]} />
      <mesh name="m_panel_b" geometry={nodes.m_panel_b.geometry} material={nodes.m_panel_b.material} position={[0, 0, -0.095]} />
      <mesh name="m_panel_l" geometry={nodes.m_panel_l.geometry} material={nodes.m_panel_l.material} position={[-0.455, 0, 0.064]} scale={[0.01, 0.637, 0.17]} />
      <mesh name="m_panel_r" geometry={nodes.m_panel_r.geometry} material={nodes.m_panel_r.material} position={[0.455, 0, 0.064]} scale={[0.01, 0.637, 0.17]} />
    </group>
  )
}

useGLTF.preload('/unit_pegboard.gltf')
