/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_desk.glb --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/unit_desk.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_desk" userData={{ name: 'unit_desk', hops: {} }}>
          <group name="c_scalex006" scale={[1, 0.7, 1]} userData={{ name: 'c_scalex.006', hops: {} }}>
            <group name="c_rotator_desk" position={[0, -0.259, 0.246]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1.429]} userData={{ name: 'c_rotator_desk', hops: {} }}>
              <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, -0.011, 0.089]} userData={{ hops: {}, bc: {}, name: 'Cube.006' }}>
                <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[-0.473, 0.019, 0.06]} rotation={[2.377, 0, 0]} userData={{ hops: {}, bc: {}, name: 'Cube.072' }} />
                <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[0.471, 0.012, 0.06]} userData={{ auto_smooth_angle: 1.0471975803375244, use_auto_smooth: 1, hops: {}, bc: {}, name: 'Cube.012' }} />
                <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[0.473, 0.019, 0.06]} rotation={[3.041, 0, 0]} userData={{ hops: {}, bc: {}, name: 'Cube.014', constraints: '[{"type": "TRACK_TO", "name": "Track To", "enabled": true, "influence": 1.0, "target": {"object": "Empty", "bone": null}, "track_axis": "TRACK_Y", "up_axis": "UP_Z", "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
              </mesh>
            </group>
            <group name="Empty011" position={[-0.479, 0, 0.067]} scale={[0.025, 0.036, 0.025]} userData={{ name: 'Empty.011', hops: {} }} />
            <group name="Empty012" position={[0.479, 0, 0.067]} scale={[0.025, 0.036, 0.025]} userData={{ name: 'Empty.012', hops: {} }} />
            <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0, 0.479, 0.067]} scale={[1, 1.429, 1]} userData={{ hops: {}, bc: {}, name: 'Cube.002' }} />
            <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[0, -0.376, 0.257]} scale={[1, 1.429, 1]} userData={{ hops: {}, bc: {}, name: 'Cube.003' }} />
            <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[0, 0, -0.1]} scale={[1, 1.429, 1]} userData={{ hops: {}, use_auto_smooth: 1, bc: {}, name: 'Cube.004' }} />
            <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0, -0.246, 0.067]} scale={[1, 1.429, 1]} userData={{ hops: {}, bc: {}, use_auto_smooth: 1, auto_smooth_angle: 1.0471975803375244, name: 'Cube.005' }} />
            <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[0, 0.263, 0.067]} scale={[1, 1.429, 1]} userData={{ hops: {}, bc: {}, name: 'Cube.007' }} />
          </group>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.001', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.012", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
            <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[-0.006, -0.021, 0.16]} rotation={[-2.236, 0, 0]} userData={{ hops: {}, bc: {}, name: 'Cube.071' }}>
              <group name="Empty" position={[0, -0.064, 0.082]} userData={{ name: 'Empty', hops: {} }} />
            </mesh>
          </mesh>
          <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.009', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.011", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
            <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={nodes.Cube070.material} position={[0.006, -0.021, 0.16]} rotation={[-2.236, 0, 0]} userData={{ hops: {}, bc: {}, name: 'Cube.070' }} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_desk.glb')
