/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_small_panel.glb -o ./src/models/unit_small_panel.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelSmallPanel(props) {
  const { nodes, materials } = useGLTF('/unit_small_panel.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_small_panel" userData={{ name: 'unit_small_panel', hops: {} }}>
          <group name="c_scalex004" scale={[1, 0.35, 1]} userData={{ name: 'c_scalex.004', hops: {} }} />
          <mesh name="m_small_panel" geometry={nodes.m_small_panel.geometry} material={materials.Wood} position={[0, 0, -0.101]} userData={{ hops: {}, use_auto_smooth: 1, bc: {}, name: 'm_small_panel', constraints: '[{"type": "COPY_SCALE", "name": "Copy Scale", "enabled": true, "influence": 1.0, "target": {"object": "c_scalex.004", "bone": null}, "use": {"x": true, "y": false, "z": false}, "use_offset": false, "power": 1.0, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_small_panel.glb')
