/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_frame.glb -o ./src/models/unit_frame.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function ModelFrame(props) {
  const { nodes, materials } = useGLTF('/unit_frame.glb')
  const frameMaterial = React.useMemo(
    () =>
      materials.Wood ??
      Object.values(materials)[0] ??
      new THREE.MeshStandardMaterial({ color: '#8b6b4a', roughness: 0.7, metalness: 0.1 }),
    [materials],
  )
  return (
    <group {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_frame" userData={{ name: 'unit_frame', hops: {} }}>
          <group name="c_scalex003" scale={[1, 1.75, 1]} userData={{ name: 'c_scalex.003', hops: {} }}>
            <group name="c_frame_l" position={[-0.442, 0.007, -0.151]} scale={[1, 0.571, 1]} userData={{ name: 'c_frame_l', hops: {} }} />
            <group name="c_frame_r" position={[0.442, 0.007, -0.151]} scale={[1, 0.571, 1]} userData={{ name: 'c_frame_r', hops: {} }} />
          </group>
          <mesh name="m_frame_l" geometry={nodes.m_frame_l.geometry} material={frameMaterial} position={[-0.442, 0.012, -0.151]} userData={{ hops: {}, auto_smooth_angle: 1.0471975803375244, use_auto_smooth: 1, bc: {}, name: 'm_frame_l', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_frame_l", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_frame_r" geometry={nodes.m_frame_r.geometry} material={frameMaterial} position={[0.442, 0.012, -0.151]} userData={{ hops: {}, auto_smooth_angle: 1.0471975803375244, use_auto_smooth: 1, bc: {}, name: 'm_frame_r', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_frame_r", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_frame.glb')
