/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_small_door.glb -o ./src/models/unit_small_door.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModelSmallDoor(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/unit_small_door.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_small_door_foot" userData={{ name: 'unit_small_door_foot', hops: {} }}>
          <group name="c_rotator_dl_r001" position={[0.479, 0, 0.247]} rotation={[Math.PI, -1.165, Math.PI]} scale={0.061} userData={{ name: 'c_rotator_dl_r.001', hops: {}, constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.014", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
            <group name="m_door_r001" position={[-0.134, 0, -0.303]} rotation={[0, 0.014, 0]} scale={16.281} userData={{ name: 'm_door_r.001', hops: {}, bc: {} }}>
              <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials.Wood} userData={{ hops: {}, bc: {}, use_auto_smooth: 1 }} />
              <mesh name="Cube023_2" geometry={nodes.Cube023_2.geometry} material={materials.Metal} userData={{ hops: {}, bc: {}, use_auto_smooth: 1 }} />
            </group>
          </group>
          <group name="c_rotator_ld_l001" position={[-0.479, 0, 0.247]} rotation={[-Math.PI, 1.142, -Math.PI]} scale={0.061} userData={{ name: 'c_rotator_ld_l.001', hops: {}, constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
            <group name="m_door_l001" position={[0.15, 0, -0.306]} rotation={[0, 0.008, 0]} scale={16.281} userData={{ name: 'm_door_l.001', hops: {}, bc: {} }}>
              <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.Wood} userData={{ hops: {}, bc: {} }} />
              <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials.Metal} userData={{ hops: {}, bc: {} }} />
            </group>
          </group>
          <group name="c_scalex001" scale={[1, 0.35, 1]} userData={{ name: 'c_scalex.001', hops: {} }}>
            <group name="Empty002" position={[-0.479, 0, 0.067]} scale={[0.025, 0.071, 0.025]} userData={{ name: 'Empty.002', hops: {} }} />
            <group name="Empty014" position={[0.479, 0, 0.067]} scale={[0.025, 0.071, 0.025]} userData={{ name: 'Empty.014', hops: {} }} />
            <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.Wood} position={[0, 0.48, 0.067]} scale={[1, 2.857, 1]} userData={{ hops: {}, bc: {}, name: 'Cube.021' }} />
            <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.Wood} position={[0, -0.477, -0.1]} scale={[1, 2.857, 1]} userData={{ hops: {}, use_auto_smooth: 1, bc: {}, name: 'Cube.023' }} />
          </group>
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.Wood} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.010', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.014", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Wood} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.011', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Wood} position={[0, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.016' }} />
          <mesh name="m_foot_l001" geometry={nodes.m_foot_l001.geometry} material={materials.Wood} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_foot_l.001', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_foot_r001" geometry={nodes.m_foot_r001.geometry} material={materials.Wood} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_foot_r.001', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.014", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_hinge_l001" geometry={nodes.m_hinge_l001.geometry} material={materials.Metal} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_hinge_l.001', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_hinge_r001" geometry={nodes.m_hinge_r001.geometry} material={materials.Metal} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_hinge_r.001', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.014", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_small_door.glb')
