/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_open_small.glb -o ./src/models/unit_open_small.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelOpenSmall(props) {
  const { nodes, materials } = useGLTF('/unit_open_small.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_small_open_leg" userData={{ name: 'unit_small_open_leg', hops: {} }}>
          <group name="c_scalex" scale={[1, 0.35, 1]} userData={{ name: 'c_scalex', hops: {} }}>
            <group name="Empty013" position={[0.479, 0, 0.067]} scale={[0.025, 0.071, 0.025]} userData={{ name: 'Empty.013', hops: {} }} />
            <group name="Empty015" position={[-0.479, 0, 0.067]} scale={[0.025, 0.071, 0.025]} userData={{ name: 'Empty.015', hops: {} }} />
            <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials.Wood} position={[0, 0.48, 0.068]} scale={[1, 2.857, 1]} userData={{ hops: {}, bc: {}, name: 'Cube.041' }} />
            <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials.Wood} position={[0, -0.477, -0.1]} scale={[1, 2.857, 1]} userData={{ hops: {}, use_auto_smooth: 1, bc: {}, name: 'Cube.043' }} />
          </group>
          <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Wood} position={[-0.479, 0, 0.068]} userData={{ hops: {}, bc: {}, name: 'Cube.015', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.015", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Wood} position={[0.479, 0, 0.068]} userData={{ hops: {}, bc: {}, name: 'Cube.018', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.013", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_foot_l" geometry={nodes.m_foot_l.geometry} material={materials.Wood} position={[-0.479, 0, 0]} userData={{ hops: {}, bc: {}, name: 'm_foot_l', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.015", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_foot_r" geometry={nodes.m_foot_r.geometry} material={materials.Wood} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_foot_r', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "Empty.013", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_open_small.glb')
