/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_desk.glb -o ./src/models/unit_desk.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelDesk(props) {
  const { scene } = useGLTF('/unit_desk.glb')
  const clonedScene = React.useMemo(() => scene.clone(true), [scene])

  return (
    <group {...props} dispose={null}>
      <primitive object={clonedScene} />
    </group>
  )
}

useGLTF.preload('/unit_desk.glb')
