/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_large_door.glb -o ./src/models/unit_large_door.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModelLargeDoor(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/unit_large_door.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_large_door_foot" userData={{ name: 'unit_large_door_foot', hops: {} }}>
          <group name="c_rotator_dl_r" position={[0.479, 0, 0.247]} rotation={[Math.PI, -1.18, Math.PI]} scale={0.061} userData={{ name: 'c_rotator_dl_r', hops: {}, constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_r.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
            <group name="m_door_r" position={[-0.144, 0, -0.307]} scale={16.281} userData={{ name: 'm_door_r', hops: {}, bc: {}, constraints: '[{"type": "COPY_ROTATION", "name": "Copy Rotation", "enabled": true, "influence": 1.0, "target": {"object": "c_rotator_dl_r", "bone": null}, "use": {"x": false, "y": false, "z": true}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "mix_mode": "REPLACE", "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
              <mesh name="Cube098" geometry={nodes.Cube098.geometry} material={materials.Wood} userData={{ hops: {}, bc: {}, use_auto_smooth: 1 }} />
              <mesh name="Cube098_1" geometry={nodes.Cube098_1.geometry} material={materials.Metal} userData={{ hops: {}, bc: {}, use_auto_smooth: 1 }} />
            </group>
          </group>
          <group name="c_rotator_ld_l" position={[-0.479, 0, 0.248]} rotation={[-Math.PI, 1.134, -Math.PI]} scale={0.061} userData={{ name: 'c_rotator_ld_l', hops: {}, constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_l.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
            <group name="m_door_l" position={[0.164, 0, -0.299]} scale={16.281} userData={{ name: 'm_door_l', hops: {}, bc: {}, constraints: '[{"type": "COPY_ROTATION", "name": "Copy Rotation", "enabled": true, "influence": 1.0, "target": {"object": "c_rotator_ld_l", "bone": null}, "use": {"x": false, "y": false, "z": true}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "mix_mode": "REPLACE", "owner_space": "WORLD", "target_space": "WORLD"}]' }}>
              <mesh name="Cube101" geometry={nodes.Cube101.geometry} material={materials.Wood} userData={{ hops: {}, bc: {} }} />
              <mesh name="Cube101_1" geometry={nodes.Cube101_1.geometry} material={materials.Metal} userData={{ hops: {}, bc: {} }} />
            </group>
          </group>
          <group name="c_scalx" position={[0, 0, 0.067]} scale={[1, 0.7, 1]} userData={{ name: 'c_scalx', hops: {} }}>
            <group name="c_panel_l002" position={[-0.479, 0, 0]} scale={[0.05, 0.071, 0.05]} userData={{ name: 'c_panel_l.002', hops: {} }} />
            <group name="c_panel_r002" position={[0.479, 0, 0]} scale={[0.05, 0.071, 0.05]} userData={{ name: 'c_panel_r.002', hops: {} }} />
            <mesh name="Cube097" geometry={nodes.Cube097.geometry} material={materials.Wood} position={[0, 0.479, 0]} scale={[1, 1.429, 1]} userData={{ hops: {}, bc: {}, name: 'Cube.097' }} />
            <mesh name="Cube099" geometry={nodes.Cube099.geometry} material={materials.Wood} position={[0, 0, -0.168]} scale={[1, 1.429, 1]} userData={{ hops: {}, use_auto_smooth: 1, bc: {}, name: 'Cube.099' }} />
            <mesh name="Cube118" geometry={nodes.Cube118.geometry} material={materials.Wood} position={[0, -0.294, 0]} scale={[1, 1.429, 0.96]} userData={{ hops: {}, bc: {}, name: 'Cube.118' }} />
            <mesh name="Cube119" geometry={nodes.Cube119.geometry} material={materials.Wood} position={[0, 0.001, 0]} scale={[1, 1.429, 0.96]} userData={{ hops: {}, bc: {}, name: 'Cube.119' }} />
            <mesh name="Cube120" geometry={nodes.Cube120.geometry} material={materials.Wood} position={[0, 0.289, 0]} scale={[1, 1.429, 0.96]} userData={{ hops: {}, bc: {}, name: 'Cube.120' }} />
          </group>
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Wood} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.008', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_l.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="Cube096" geometry={nodes.Cube096.geometry} material={materials.Wood} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.096', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_r.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="Cube117" geometry={nodes.Cube117.geometry} material={materials.Wood} position={[0, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'Cube.117' }} />
          <mesh name="m_foot_l002" geometry={nodes.m_foot_l002.geometry} material={materials.Wood} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_foot_l.002', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_l.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_foot_r002" geometry={nodes.m_foot_r002.geometry} material={materials.Wood} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_foot_r.002', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_r.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_hinge_l" geometry={nodes.m_hinge_l.geometry} material={materials.Metal} position={[-0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_hinge_l', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_l.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
          <mesh name="m_hinge_r" geometry={nodes.m_hinge_r.geometry} material={materials.Metal} position={[0.479, 0, 0.067]} userData={{ hops: {}, bc: {}, name: 'm_hinge_r', constraints: '[{"type": "COPY_LOCATION", "name": "Copy Location", "enabled": true, "influence": 1.0, "target": {"object": "c_panel_r.002", "bone": null}, "use": {"x": true, "y": false, "z": false}, "invert": {"x": false, "y": false, "z": false}, "use_offset": false, "owner_space": "WORLD", "target_space": "WORLD"}]' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_large_door.glb')
