/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/unit_large_small.glb -o ./src/models/unit_large_small.jsx --keepgroups --keepnames --meta 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelLargeSmall(props) {
  const { nodes, materials } = useGLTF('/unit_large_small.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene" userData={{ bc: { shape: null, collection: null, recall_collection: {}, bevel: null, lattice: null, running: 0, original_active: null, last: { surface: 'OBJECT' }, plane: null, snap: { hit: false }, empty: null, location: [0, 0, 0], wedge_point: 2, slice: null, inset: null, stored_shape: {} }, hops: { collection: {} }, gltf_constraints_last_count: 44, gltf_constraints_auto_bake: 1 }}>
        <group name="unit_large_panel" userData={{ name: 'unit_large_panel', hops: {} }}>
          <group name="c_scalex005" scale={[1, 0.7, 1]} userData={{ name: 'c_scalex.005', hops: {} }}>
            <mesh name="m_large_panel" geometry={nodes.m_large_panel.geometry} material={materials.Wood} position={[0, 0, -0.101]} scale={[1, 1.451, 1]} userData={{ hops: {}, use_auto_smooth: 1, bc: {}, name: 'm_large_panel' }} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/unit_large_small.glb')
